### ISSUE TITLE
Is there a way to make a header element sit below the scrollable content?

### ISSUE THREAD

**Issue by alaughlin** [kanelloc/react-native-animated-header-scroll-view#100]
I'd like to position a sticky/fixed element inside the header that the will be covered by the scrollable content. When the user scrolls, I want the element inside the header to remain in place while the header shrinks and the content covers it. I've tried adding the element to the `HeaderNavbarComponent` because it is fixed, but that component sits on top of the scrollable content instead of below it. I've tried messing with z-indexes but nothing seems to work. Is there a way to do this?

**Comment by alaughlin** [comment]
Going to close this for now, as I've solved this by patching this library to add support for a fixed HeaderComponent

Attached a diff if anyone is curious how to do this!

[@kanelloc+react-native-animated-header-scroll-view+1.0.0.patch](https://github.com/kanelloc/react-native-animated-header-scroll-view/files/13506777/%40kanelloc%2Breact-native-animated-header-scroll-view%2B1.0.0.patch)

**Comment by kanelloc** [comment]
Hey @alaughlin !! Thanks for using the library!! You can also open a PR with the above patch 😃
