### ISSUE TITLE
What numbers for header image aspect ratio?

### ISSUE THREAD

**Issue by harisnaufal** [kanelloc/react-native-animated-header-scroll-view#24]
Currently I have an issue with header image aspect ratio. Can you do explain what default numbers used by this library? Because when I force to use aspect ration on props, the whole screen got affected not just only the header.

Hope you reply my message. Thanks in advance.

**Comment by kanelloc** [comment]
Hey @harisnaufal !
That's because the `style` prop is about styling the `ScrollView`. It's not dedicated to the image.

I'll add another `imageAspectRatio` property so you can use it specifically for the image 😄 
I'll release a new version today.

Thanks a lot for your input!!

**Comment by kanelloc** [comment]
@harisnaufal you can update library version to 0.10.0 and use `imageStyle` property to change the aspect ratio

**Comment by harisnaufal** [comment]
sure will update the libary, thanks a lot. Anyway, the library was cool great job!
