### ISSUE TITLE
Refreshing support

### ISSUE THREAD

**Issue by AlirezaHadjar** [kanelloc/react-native-animated-header-scroll-view#41]
Does it support the pull-to-refresh feature?

**Comment by AlirezaHadjar** [comment]
Found the example actually!
[https://github.com/kanelloc/react-native-animated-header-scroll-view/blob/main/example/src/screens/RefreshControlExample.tsx](Example)
Thanks.

**Comment by kanelloc** [comment]
@AlirezaHadjar pull-to-refresh is currently supported on both `AnimatedScrollView` and `AnimatedFlatList`
