### ISSUE TITLE
Top Bar Height on Android

### ISSUE THREAD

**Issue by harisnaufal** [kanelloc/react-native-animated-header-scroll-view#43]
Hi, I have an issue regarding the top bar on android devices. The height is bigger than iOS -- seems like the top had a big padding on it. You have a props `headerMaxHeight` but it doesn't work good with what I want it to be.

Hope you can figure it out on your android devices. The library was cool and really like it!
Thanks in advance.

**Comment by harisnaufal** [comment]
![WhatsApp Image 2023-02-21 at 10 39 41](https://user-images.githubusercontent.com/26920810/220241911-8227ec5c-daaf-409d-ba2e-2dffc98c5bd3.jpeg)

Like this.

**Comment by kanelloc** [comment]
Hey @harisnaufal !
You can use `topBarHeight` to adjust the height of the top bar.
Check also here: https://github.com/kanelloc/react-native-animated-header-scroll-view#props

**Comment by kanelloc** [comment]
@harisnaufal Thanks for using this library 🎉 🎉 . 
If you like it please leave it a ⭐
