### ISSUE TITLE
TopNavBarComponent styles

### ISSUE THREAD

**Issue by shukerullah** [kanelloc/react-native-animated-header-scroll-view#44]
I would like to request a feature for the ability to customize the style of the top nav bar. Currently, I am unable to use black as a background color and would appreciate the option to pass my own styles that override default styles.

I would like to change background color, elevation, paddingTop.

Thank you.

**Comment by kanelloc** [comment]
Hi @shukerullah `TopNavBarComponent` is required and fully customizable. 
There is no option for a default `topNavBarComponent` that's why there is no option for customizing the style of the top nav bar.
You should provide your own component
