### ISSUE TITLE
Accessing the ref of the internal ScrollView to use scrollTo() method?

### ISSUE THREAD

**Issue by PlayBlue7** [kanelloc/react-native-animated-header-scroll-view#46]
Hi, I was wondering if there is any way to access the ref of the internal ScrollView of this component to call the scrollTo method? If not, is there any way to scroll to a certain item in the AnimatedScrollView?

Thanks!

**Comment by kanelloc** [comment]
Hey @PlayBlue7! I'm working on implementing forward ref functionality atm. 😄
