### ISSUE TITLE
Weird white view

### ISSUE THREAD

**Issue by cspeer** [kanelloc/react-native-animated-header-scroll-view#60]
Sorry for the shitty title, but it's really hard to describe.

My app has a light and a dark mode and everything works really smoothly, except when I'm in dark mode and scroll up a white view becomes visible that I do not seem to have control over.
Here are 2 screenshots, that hopefully can explain the issue better:

![IMG_7952](https://github.com/kanelloc/react-native-animated-header-scroll-view/assets/326824/bc12aeaa-42e8-418f-ad64-394064f681b8)

This is the view when everything is scrolled down. You can see that the red area covers everything. But when I scroll up, that white/redish area right above the red part becomes visible and will stay there when everything is all scrolled up. It appears to be the view that manages the fade out effect.

![IMG_7953](https://github.com/kanelloc/react-native-animated-header-scroll-view/assets/326824/dd9c92ff-f52c-477c-8d0b-a99f207e47d3)

Am I missing something? Is there some kind of property that controls the color of this view?

Thanks a lot,
Chris

// Edit
Here's a quick video of what I'm seeing, maybe that helps: https://imgur.com/a/fWGZ7Bn

**Comment by rumfiske** [comment]
Same here

**Comment by kanelloc** [comment]
Sorry for the delay!! I'll open a PR this weekend with a fix.
I'll keep you posted 👍

**Comment by cspeer** [comment]
Great news @kanelloc - thank you so much!
Have you got an update for us?

**Comment by kanelloc** [comment]
Please check the above PR, update to the latest package and let me know if have any other issue

**Comment by cspeer** [comment]
Awesome! Thank you so much @kanelloc

**Comment by kanelloc** [comment]
@cspeer can you confirm if the latest version resolved the issue?

**Comment by cspeer** [comment]
I briefly tested it and was unable to reproduce the problem as described in my initial post!
