### ISSUE TITLE
Fix white header visible when we scroll down

### ISSUE THREAD

**Issue by rumfiske** [kanelloc/react-native-animated-header-scroll-view#61]
Pleaske make props for theese 2 CSS settings so we can put 0 as elevation and transparent for header.
![Code_p5pEPrrKMh](https://github.com/kanelloc/react-native-animated-header-scroll-view/assets/59709554/abf7fa36-9b09-4d18-a1f5-25e29dde66d5)

**Comment by kanelloc** [comment]
Please check the above PR, update to the latest package and let me know if have any other issue

**Comment by rumfiske** [comment]
Still same issue. We need to have a prop for this specific style. Still need to change it manually. :( But good work with everything else bro
![Code_JhniVIRdyT](https://github.com/kanelloc/react-native-animated-header-scroll-view/assets/59709554/b75ba2a9-b330-45ac-ad90-9ad82be4e328)
![Airplay_KyK51xRetn](https://github.com/kanelloc/react-native-animated-header-scroll-view/assets/59709554/e7720cfa-3225-4574-a8e8-f7f1e30619c9)

**Comment by kanelloc** [comment]
@rumfiske can you attach a video to understand exactly the use case?
I'm testing it locally with different background colors and it works as expected.

**Comment by charlesoestergaard** [comment]
It has to be a value that can be dynamicly set, right now its hardcoded into the component. I fixed it my self the PR is here ->https://github.com/kanelloc/react-native-animated-header-scroll-view/issues/102
